# Generated by Django 4.2.25 on 2025-10-31 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_alter_course_colour_alter_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours_target', models.DecimalField(blank=True, decimal_places=2, help_text='Target study hours per week.', max_digits=5, null=True)),
                ('weekly_lessons_target', models.PositiveIntegerField(blank=True, help_text='How many lessons/modules do you aim to complete per week?', null=True)),
                ('study_days_per_week', models.PositiveSmallIntegerField(default=5, help_text='How many days per week will you study? (1–7).')),
                ('total_required_lessons', models.PositiveIntegerField(blank=True, help_text='How many lessons/modules need to be completed for the milestone?', null=True)),
                ('milestone_name', models.CharField(blank=True, help_text="e.g., 'Assignment 2' or 'Course completion'", max_length=120, null=True)),
                ('milestone_date', models.DateField(blank=True, help_text='Deadline for the milestone.', null=True)),
                ('avg_hours_per_lesson', models.DecimalField(blank=True, decimal_places=2, help_text='If set, we can estimate hours needed from lesson targets.', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(check=models.Q(('study_days_per_week__gte', 1), ('study_days_per_week__lte', 7)), name='goals_days_between_1_and_7'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(check=models.Q(('weekly_hours_target__isnull', False), ('weekly_lessons_target__isnull', False), ('total_required_lessons__isnull', False), _connector='OR'), name='goals_need_some_target'),
        ),
    ]
