# Generated by Django 4.2.25 on 2025-10-31 14:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import goals.models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='weekly_hours_target',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Target study hours per week in 0.5 steps.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), goals.models.validate_half_hours]),
        ),
    ]
