# Generated by Django 4.2.25 on 2025-11-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_weekly_hours_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('hours_completed', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('hours_target', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('lessons_target', models.PositiveIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='goals.goal')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='goaloutcome',
            constraint=models.UniqueConstraint(fields=('goal', 'week_start'), name='unique_goal_week'),
        ),
    ]
