# Generated by Django 4.2.25 on 2025-10-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='colour',
            field=models.CharField(blank=True, choices=[('#6366F1', 'Indigo'), ('#7C3AED', 'Violet'), ('#10B981', 'Emerald'), ('#0EA5E9', 'Sky'), ('#F59E0B', 'Amber'), ('#F43F5E', 'Rose'), ('#475569', 'Slate'), ('', 'No colour')], default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=140),
        ),
    ]
